'use client';

import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { io } from 'socket.io-client';
import { Hexagon, Users, Clock, Bot, User, Phone, Search, LogOut } from 'lucide-react';
import Link from 'next/link';
import { QRCodeSVG } from 'qrcode.react';
import toast from 'react-hot-toast';

// Connect to the same WebSocket server
const socket = io('http://localhost:3001');

export default function CRMConsole() {
    const [conversations, setConversations] = useState({});
    const [activeChatId, setActiveChatId] = useState(null);
    const [isBotOnline, setIsBotOnline] = useState(false);
    const [botStatus, setBotStatus] = useState('waiting');
    const [qrCode, setQrCode] = useState('');
    const messagesEndRef = useRef(null);

    // Auto-scroll logic
    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [conversations, activeChatId]);

    useEffect(() => {
        // 1. Fetch Historical Database from Backend
        const fetchHistory = async () => {
            try {
                const res = await fetch('http://localhost:3001/api/conversations');
                if (res.ok) {
                    const data = await res.json();
                    // Convert string timestamps back to Date objects
                    const parsedData = {};
                    for (let phone in data) {
                        parsedData[phone] = data[phone].map(msg => ({
                            ...msg,
                            time: new Date(msg.time)
                        }));
                    }
                    setConversations(parsedData);
                    console.log('Loaded historical DB:', parsedData);
                }
            } catch (e) {
                console.error('Error fetching DB:', e);
            }
        };
        fetchHistory();

        // 2. Setup Real-time Socket Connection
        // Check initial connection status
        socket.on('connect', () => {
            // We wait for initial_status rather than assuming online
        });

        socket.on('initial_status', (data) => {
            setBotStatus(data.status);
            if (data.qr && data.status === 'waiting') {
                setQrCode(data.qr);
            }
            setIsBotOnline(data.status === 'connected' || data.status === 'ready');
        });

        socket.on('qr', (qr) => {
            setQrCode(qr);
            setBotStatus('waiting');
            setIsBotOnline(false);
        });

        socket.on('disconnect', () => {
            setIsBotOnline(false);
            setBotStatus('waiting');
        });

        socket.on('authenticated', () => {
            setBotStatus('connected');
            setIsBotOnline(true);
        });

        socket.on('ready', () => {
            setBotStatus('ready');
            setIsBotOnline(true);
        });

        socket.on('disconnected', () => {
            // Fired if the user logs out from their WhatsApp Phone App
            setBotStatus('waiting');
            setIsBotOnline(false);
        });

        // Handle incoming messages from leads
        socket.on('message_received', (data) => {
            const chatId = data.from;
            setConversations(prev => {
                const chatHistory = prev[chatId] || [];
                return {
                    ...prev,
                    [chatId]: [...chatHistory, { type: 'incoming', text: data.body, time: new Date(data.timestamp), id: data.id }]
                };
            });
            // Auto-select the first chat if none is active
            if (!activeChatId) setActiveChatId(chatId);
        });

        // Handle outgoing messages generated by Gemini
        socket.on('message_sent', (data) => {
            const chatId = data.to;
            setConversations(prev => {
                const chatHistory = prev[chatId] || [];
                return {
                    ...prev,
                    [chatId]: [...chatHistory, { type: 'outgoing', text: data.body, time: new Date(data.timestamp), id: data.id }]
                };
            });
        });

        return () => {
            socket.off('connect');
            socket.off('initial_status');
            socket.off('qr');
            socket.off('disconnect');
            socket.off('authenticated');
            socket.off('ready');
            socket.off('disconnected');
            socket.off('message_received');
            socket.off('message_sent');
        };
    }, [activeChatId]);

    const handleDisconnect = async () => {
        const token = localStorage.getItem('cube_token');
        if (!token) return;

        try {
            setBotStatus('waiting');
            setQrCode('');
            setIsBotOnline(false);
            await fetch('http://localhost:3001/api/agent/disconnect', {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}` }
            });
        } catch (error) {
            console.error('Logout error:', error);
        }
    };

    const activeMessages = activeChatId ? conversations[activeChatId] : [];

    return (
        <div style={{ minHeight: '100vh', background: '#0a0a0a', color: '#fff', display: 'flex', flexDirection: 'column' }}>
            {/* Global Navbar occupies top space */}
            <div style={{ display: 'flex', flex: 1, overflow: 'hidden', paddingTop: '80px' }}>
                {/* Left Sidebar: Leads List */}
                <aside style={{ width: '380px', borderRight: '1px solid rgba(255,255,255,0.05)', background: 'rgba(0,0,0,0.2)', display: 'flex', flexDirection: 'column' }}>
                    <div style={{ padding: '1.5rem', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                            <h2 style={{ fontSize: '0.85rem', color: '#888', fontWeight: '500', letterSpacing: '2px', display: 'flex', alignItems: 'center', gap: '0.5rem', margin: 0, textTransform: 'uppercase' }}>
                                <Users size={14} /> ACTIVE LEADS <span style={{ background: 'rgba(255,255,255,0.1)', padding: '2px 8px', borderRadius: '12px', fontSize: '0.75rem', color: '#fff' }}>{Object.keys(conversations).length}</span>
                            </h2>
                            {/* Elite Bot Status Indicator */}
                            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                                <div
                                    className={`pulse-indicator ${isBotOnline ? 'status-online' : (botStatus === 'waiting' ? 'status-waiting' : 'status-offline')}`}
                                    title={`Status: ${botStatus}`}
                                />
                                {isBotOnline && (
                                    <button onClick={handleDisconnect} title="Disconnect WhatsApp" style={{ background: 'rgba(255,0,0,0.1)', border: '1px solid rgba(255,0,0,0.3)', borderRadius: '8px', padding: '6px', color: '#ff3366', cursor: 'pointer', display: 'flex', alignItems: 'center', transition: 'all 0.3s ease' }} onMouseOver={e => e.currentTarget.style.background = 'rgba(255,0,0,0.2)'} onMouseOut={e => e.currentTarget.style.background = 'rgba(255,0,0,0.1)'}>
                                        <LogOut size={14} />
                                    </button>
                                )}
                            </div>
                        </div>
                        <div style={{ position: 'relative' }}>
                            <Search size={16} color="#666" style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)' }} />
                            <input
                                type="text"
                                placeholder="Search conversations..."
                                style={{ width: '100%', padding: '0.8rem 1rem 0.8rem 2.5rem', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#fff', outline: 'none', fontSize: '0.9rem' }}
                            />
                        </div>
                    </div>

                    <motion.div
                        initial="hidden"
                        animate="visible"
                        variants={{
                            visible: { transition: { staggerChildren: 0.1 } }
                        }}
                        style={{ flex: 1, overflowY: 'auto' }}
                    >
                        {Object.keys(conversations).length === 0 ? (
                            <div style={{ padding: '3rem', textAlign: 'center', color: '#444', fontSize: '0.85rem', fontWeight: 500, letterSpacing: '1px' }}>
                                SCANNING FOR INCOMING LEADS...
                            </div>
                        ) : (
                            Object.entries(conversations).map(([chatId, messages]) => {
                                const lastMsg = messages[messages.length - 1];
                                const isActive = activeChatId === chatId;
                                // Format phone number (e.g., 52155... -> +52 1 55...)
                                const formattedPhone = '+' + chatId.split('@')[0];

                                return (
                                    <motion.div
                                        key={chatId}
                                        variants={{
                                            hidden: { opacity: 0, x: -20 },
                                            visible: { opacity: 1, x: 0, transition: { type: "spring", stiffness: 100 } }
                                        }}
                                        onClick={() => setActiveChatId(chatId)}
                                        style={{
                                            padding: '1.2rem 1.5rem',
                                            borderBottom: '1px solid rgba(255,255,255,0.02)',
                                            cursor: 'pointer',
                                            background: isActive ? 'linear-gradient(90deg, rgba(0,240,255,0.05) 0%, transparent 100%)' : 'transparent',
                                            borderLeft: isActive ? '3px solid var(--cube-accent)' : '3px solid transparent',
                                            transition: 'background 0.3s ease, border 0.3s ease'
                                        }}
                                        onMouseOver={e => !isActive && (e.currentTarget.style.background = 'rgba(255,255,255,0.02)')}
                                        onMouseOut={e => !isActive && (e.currentTarget.style.background = 'transparent')}
                                    >
                                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.6rem' }}>
                                            <span style={{ fontWeight: '600', color: isActive ? '#fff' : '#ccc', display: 'flex', alignItems: 'center', gap: '0.6rem', fontSize: '0.95rem' }}>
                                                <Phone size={14} color={isActive ? 'var(--cube-accent)' : '#666'} /> {formattedPhone}
                                            </span>
                                            <span style={{ fontSize: '0.7rem', color: '#666', fontWeight: 500, letterSpacing: '0.5px' }}>
                                                {lastMsg.time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                            </span>
                                        </div>
                                        <p style={{ fontSize: '0.85rem', color: '#888', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', lineHeight: '1.4' }}>
                                            {lastMsg.type === 'outgoing' ? <strong style={{ color: 'var(--cube-primary)' }}>Agent: </strong> : <span style={{ color: '#aaa' }}>Client: </span>}
                                            {lastMsg.text}
                                        </p>
                                    </motion.div>
                                )
                            })
                        )}
                    </motion.div>
                </aside>

                {/* Right Area: Live Chat Feed */}
                <main style={{ flex: 1, display: 'flex', flexDirection: 'column', position: 'relative' }}>
                    {/* Background Blur Effect */}
                    <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: '600px', height: '600px', background: 'var(--cube-primary)', filter: 'blur(200px)', opacity: 0.03, zIndex: 0, pointerEvents: 'none' }} />

                    {botStatus === 'waiting' ? (
                        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', zIndex: 1, padding: '2rem', textAlign: 'center' }}>
                            <h2 style={{ fontSize: '2rem', marginBottom: '1rem', color: '#00f0ff' }}>Agent Authentication Required</h2>
                            <p style={{ color: '#a1a1aa', fontSize: '1.1rem', marginBottom: '2rem', maxWidth: '400px' }}>Your AI Bot needs to be linked to your phone. Scan the QR code with your WhatsApp app.</p>
                            <div style={{ padding: '2rem', background: '#fff', borderRadius: '16px', border: '4px solid var(--cube-primary)', marginBottom: '1.5rem' }}>
                                {qrCode ? (
                                    <QRCodeSVG value={qrCode} size={250} />
                                ) : (
                                    <div style={{ width: '250px', height: '250px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#000' }}>
                                        Generating secure QR...
                                    </div>
                                )}
                            </div>
                            <p style={{ color: '#666', fontSize: '0.9rem' }}>Open WhatsApp on your phone &gt; Settings &gt; Linked Devices &gt; Link a Device</p>
                        </div>
                    ) : activeChatId ? (
                        <>
                            {/* Chat Header */}
                            <div style={{ padding: '1.5rem 2rem', borderBottom: '1px solid rgba(255,255,255,0.05)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'rgba(255,255,255,0.02)', zIndex: 1, backdropFilter: 'blur(10px)' }}>
                                <div>
                                    <h2 style={{ fontSize: '1.25rem', fontWeight: '600', marginBottom: '0.2rem', letterSpacing: '0.5px' }}>+{activeChatId.split('@')[0]}</h2>
                                    <p style={{ fontSize: '0.75rem', color: '#00ffaa', display: 'flex', alignItems: 'center', gap: '0.4rem', fontWeight: 500, letterSpacing: '1px', textTransform: 'uppercase' }}>
                                        <div className="pulse-indicator status-online" style={{ width: '6px', height: '6px' }} /> LIVE AI SESSION
                                    </p>
                                </div>
                                <div style={{ display: 'flex', gap: '1rem' }}>
                                    <button onClick={() => toast.success('Chat assigned to human agent.', { icon: '👤' })} style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.1)', color: '#fff', padding: '0.6rem 1.2rem', borderRadius: '8px', fontSize: '0.8rem', cursor: 'pointer', fontWeight: 500, transition: 'all 0.3s ease' }} onMouseOver={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.08)'; e.currentTarget.style.borderColor = 'rgba(255,255,255,0.2)' }} onMouseOut={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; e.currentTarget.style.borderColor = 'rgba(255,255,255,0.1)' }}>Take Over Chat</button>
                                    <button onClick={() => toast.error('Lead blocked from Agent.', { icon: '🚫' })} style={{ background: 'rgba(255,51,102,0.05)', border: '1px solid rgba(255,51,102,0.3)', color: '#ff3366', padding: '0.6rem 1.2rem', borderRadius: '8px', fontSize: '0.8rem', cursor: 'pointer', fontWeight: 500, transition: 'all 0.3s ease' }} onMouseOver={e => { e.currentTarget.style.background = 'rgba(255,51,102,0.15)'; e.currentTarget.style.boxShadow = '0 0 15px rgba(255,51,102,0.2)' }} onMouseOut={e => { e.currentTarget.style.background = 'rgba(255,51,102,0.05)'; e.currentTarget.style.boxShadow = 'none' }}>Block Lead</button>
                                </div>
                            </div>

                            {/* Chat Messages */}
                            <div style={{ flex: 1, overflowY: 'auto', padding: '2rem', paddingBottom: '4rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', zIndex: 1 }}>
                                <div style={{ textAlign: 'center', margin: '2rem 0' }}>
                                    <span style={{ background: 'rgba(255,255,255,0.05)', padding: '0.5rem 1rem', borderRadius: '100px', fontSize: '0.75rem', color: '#666', letterSpacing: '1px' }}>
                                        SECURE CUBE SESSION ESTABLISHED
                                    </span>
                                </div>

                                <AnimatePresence initial={false}>
                                    {activeMessages.map((msg, index) => {
                                        const isBot = msg.type === 'outgoing';
                                        return (
                                            <motion.div
                                                key={msg.id || index}
                                                initial={{ opacity: 0, y: 15, scale: 0.95 }}
                                                animate={{ opacity: 1, y: 0, scale: 1 }}
                                                transition={{ type: 'spring', stiffness: 200, damping: 20 }}
                                                style={{
                                                    alignSelf: isBot ? 'flex-start' : 'flex-end',
                                                    display: 'flex',
                                                    flexDirection: isBot ? 'row' : 'row-reverse',
                                                    gap: '1rem',
                                                    maxWidth: '85%'
                                                }}
                                            >
                                                {/* Avatar */}
                                                <div style={{
                                                    width: '38px', height: '38px', borderRadius: '50%', flexShrink: 0,
                                                    background: isBot ? 'linear-gradient(135deg, rgba(0,240,255,0.15), rgba(0,136,255,0.15))' : 'rgba(255,255,255,0.03)',
                                                    border: `1px solid ${isBot ? 'rgba(0,240,255,0.4)' : 'rgba(255,255,255,0.08)'}`,
                                                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                                                    color: isBot ? 'var(--cube-accent)' : '#aaa',
                                                    boxShadow: isBot ? '0 0 15px rgba(0,136,255,0.2)' : 'none'
                                                }}>
                                                    {isBot ? <Hexagon size={18} strokeWidth={2.5} /> : <User size={18} />}
                                                </div>

                                                {/* Bubble */}
                                                <div style={{ display: 'flex', flexDirection: 'column', alignItems: isBot ? 'flex-start' : 'flex-end' }}>
                                                    <div style={{ display: 'flex', alignItems: 'baseline', gap: '0.6rem', marginBottom: '0.4rem', flexDirection: isBot ? 'row' : 'row-reverse' }}>
                                                        <span style={{ fontSize: '0.8rem', color: isBot ? '#fff' : '#ccc', fontWeight: '600', letterSpacing: '0.5px' }}>
                                                            {isBot ? 'Agent CUBE' : 'Customer'}
                                                        </span>
                                                        <span style={{ fontSize: '0.7rem', color: '#666', fontWeight: 500 }}>
                                                            {msg.time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                                        </span>
                                                    </div>
                                                    <div style={{
                                                        background: isBot ? 'rgba(10, 15, 20, 0.7)' : 'rgba(30, 30, 35, 0.6)',
                                                        border: isBot ? '1px solid rgba(0,240,255,0.25)' : '1px solid rgba(255,255,255,0.08)',
                                                        padding: '1rem 1.4rem',
                                                        borderRadius: isBot ? '4px 20px 20px 20px' : '20px 4px 20px 20px',
                                                        fontSize: '0.95rem',
                                                        lineHeight: '1.6',
                                                        color: isBot ? '#fff' : '#eaeaea',
                                                        whiteSpace: 'pre-wrap',
                                                        boxShadow: isBot ? '0 8px 24px rgba(0,0,0,0.4), inset 0 0 20px rgba(0,240,255,0.03)' : '0 4px 12px rgba(0,0,0,0.2)',
                                                        backdropFilter: 'blur(20px)'
                                                    }}>
                                                        {msg.text}
                                                    </div>
                                                </div>
                                            </motion.div>
                                        )
                                    })}
                                </AnimatePresence>
                                <div ref={messagesEndRef} />
                            </div>
                        </>
                    ) : (
                        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: '#666', zIndex: 1 }}>
                            <Hexagon size={48} color="#333" style={{ marginBottom: '1rem' }} />
                            <h3 style={{ fontSize: '1.2rem', fontWeight: '400', marginBottom: '0.5rem', color: '#888' }}>CRM Console Ready</h3>
                            <p style={{ fontSize: '0.9rem' }}>Select a conversation from the left to monitor the AI.</p>
                        </div>
                    )}
                </main>
            </div>
        </div>
    );
}
